version: "3"
services:
  mysql:
    image: mysql:5.6
    volumes:
      - ./db:/var/lib/mysql
      - ./compose/mysql:/etc/mysql/mysql.conf.d
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=notebook
      - LANG=C.UTF-8
    ports:
      - "3306:3306"
    restart: always
  web:
    image: node:12
    working_dir: /server
    volumes:
      - ./server:/server
    ports:
      - "3001:3001"
    command: ["./script/wait-for-it.sh", "mysql:3306", "--", "npm", "run", "start:prod"]
  nginx:
    image: nginx
    volumes:
      - ./view:/notebook
      - ./compose/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
